export const getAssets = () => {
  return {
    DEVFLOW_LOGO: '/images/site-logo.svg',
    SUN: '/icons/sun.svg',
    MOON: '/icons/moon.svg',
    STAR: '/icons/star.svg',
    STAR_OUTLINE: '/icons/star-red.svg',
    SYSTEM: '/icons/computer.svg',
    HAMBURGER: '/icons/hamburger.svg',
    HOME: '/icons/home.svg',
    USERS: '/icons/users.svg',
    SUITCASE: '/icons/suitcase.svg',
    TAG: '/icons/tag.svg',
    USER: '/icons/user.svg',
    QUESTION: '/icons/question.svg',
    SEARCH: '/icons/search.svg',
    AVATAR: '/icons/avatar.svg',
    ARROW_RIGHT: '/icons/arrow-right.svg',
    ARROW_LEFT: '/icons/arrow-left.svg',
    ACCOUNT: '/icons/account.svg',
    SIGNUP: '/icons/sign-up.svg',
    CHEVRON_RIGHT: '/icons/chevron-right.svg',
    CLOSE: '/icons/close.svg',
    LIGHT_ILLUSTRATION: '/images/light-illustration.png',
    DARK_ILLUSTRATION: '/images/dark-illustration.png',
    LIKE: '/icons/like.svg',
    MESSAGE: '/icons/message.svg',
    EYE: '/icons/eye.svg'
  };
};
