import { config } from 'dotenv';

config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const {
  NODE_ENV,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY,
  NEXT_PUBLIC_CLERK_SIGN_IN_URL,
  NEXT_PUBLIC_CLERK_SIGN_UP_URL,
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
  NEXT_PUBLIC_TINY_EDITOR_API_KEY,

  MONGODB_USER,
  MONGODB_USER_PASSWORD,
  MONGODB_APP_NAME,
  MONGODB_CLUSTER_NAME,
  MONGODB_DATABASE_NAME,
  MONGODB_URI
} = process.env;
