import type { Metadata } from 'next';

import Navbar from '@/components/Navbar/Navbar';

import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar />
      <section className='flex justify-center items-center w-full min-h-screen'>{children}</section>
    </main>
  );
}
